### ISSUE TITLE
Cloud Run service name detection and replacement algorithm for README parsing flawed

### ISSUE THREAD

**Issue by SaketramDurbha** [GoogleCloudPlatform/serverless-sample-tester#3]
**Context:** When our program deploys samples to Cloud Run fully managed, it's necessary that it controls the name of the service that it deploys to, for two reasons: to make the service name unique (w/ the help of a random string) so that it can deploy multiple versions of the sample at the same time; and so that it's able to get its URL and delete it after the tests are completed.

The README parsing algorithm that extracts terminal commands out of the README is also responsible with detecting and replacing the service name used in the commands found in the README with the program's own unique service name.

The detection algorithm currently looks for `gcloud` commands that have `run` as one of their arguments. Then it walks from the back to the front and identifies the first argument that it finds without `--` in it to be the service name.

For example, it would correctly detect `test` to be the service name in this instance:
```
gcloud run services update test --add-cloudsql-instances=${CLOUD_SQL_CONNECTION_NAME}
```

But it would fail in this case:
```
gcloud run services update test --add-cloudsql-instances ${CLOUD_SQL_CONNECTION_NAME}
``` 
since the flag and its argument are separated and walking backwards, the algorithm would identify `${CLOUD_SQL_CONNECTION_NAME}` as the service name since it's the first argument not containing  `--`.

**Comment by grayside** [comment]
Rather than attempting to parse a particular unnamed argument from the command, it may be better to provide a constraint: a particular shell variable, or name the service the same as the directory (with some fuzz for hyphens vs. underscores)

The alternative is to investigate argument parsing in gcloud and at least partially reimplement that here.

This issue affects two "categories" in my review of the repository:
* **Experience**: Does the project provide a good experience to users?
* **Internals**: Is the implementation efficient, effective, and maintainable?
